defmodule Mercato.Repo.Migrations.CreateListings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:listings, primary_key: false) do
      add :seller_id,
          references(:users, column: :id, name: "listings_seller_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :published_at, :utc_datetime_usec
      add :status, :text, null: false
      add :quantity, :bigint, null: false
      add :currency, :text, null: false
      add :price, :bigint, null: false
      add :description, :text
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `listings` table without the `listings_seller_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:listings)
  end
end
