defmodule Mercato.Repo.Migrations.ListingDeductions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:listings) do
      add :deductions, {:array, :map}, null: false, default: []
    end
  end

  def down do
    alter table(:listings) do
      remove :deductions
    end
  end
end
