defmodule Mercato.Repo.Migrations.AddOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders, primary_key: false) do
      add :listing_id,
          references(:listings, column: :id, name: "orders_listing_id_fkey", type: :uuid),
          null: false

      add :seller_id, references(:users, column: :id, name: "orders_seller_id_fkey", type: :uuid),
        null: false

      add :buyer_id, references(:users, column: :id, name: "orders_buyer_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status, :text, null: false
      add :currency, :text, null: false
      add :unit_price, :bigint, null: false
      add :quantity, :bigint, null: false
      add :public_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:orders, [:public_id], name: "orders_unique_public_id_index")
  end

  def down do
    drop_if_exists unique_index(:orders, [:public_id], name: "orders_unique_public_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `orders` table without the `orders_buyer_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `orders` table without the `orders_seller_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `orders` table without the `orders_listing_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:orders)
  end
end
