defmodule Mercato.Repo.Migrations.IncrementUserModelBasicFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text, null: false
      add :last_name, :text
      add :handle, :text, null: false
      add :handle_changed_at, :utc_datetime_usec
      add :avatar_url, :text
      add :status, :text, null: false
      add :last_active_at, :utc_datetime_usec
    end

    create unique_index(:users, [:handle], name: "users_unique_handle_index")

    create table(:settings, primary_key: false) do
      add :handle_change_cooldown_days, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:settings)

    drop_if_exists unique_index(:users, [:handle], name: "users_unique_handle_index")

    alter table(:users) do
      remove :last_active_at
      remove :status
      remove :avatar_url
      remove :handle_changed_at
      remove :handle
      remove :last_name
      remove :first_name
    end
  end
end
