defmodule Mercato.Repo.Migrations.AddSellerDeductions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:seller_deductions, primary_key: false) do
      add :of_id,
          references(:seller_deductions,
            column: :id,
            name: "seller_deductions_of_id_fkey",
            type: :uuid
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :rate_bp, :bigint
      add :amount, :bigint
      add :kind, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:seller_deductions, [:name], name: "seller_deductions_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:seller_deductions, [:name],
                     name: "seller_deductions_unique_name_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `seller_deductions` table without the `seller_deductions_of_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:seller_deductions)
  end
end
