defmodule Mercato.Repo.Migrations.AddMarketplaceSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      # Defaults stated here as well as on the resource: a row already exists
      # on a running instance, and SQLite refuses a NOT NULL column added
      # without one to fill it with.
      add :cart_retention_days, :bigint, null: false, default: 30
      add :currency, :text, null: false, default: "USD"

      add :listing_conditions, {:array, :text},
        null: false,
        default: ["new", "like_new", "good", "fair"]

      add :listing_image_types, {:array, :text},
        null: false,
        default: ["image/jpeg", "image/png", "image/webp"]

      add :listing_image_max_bytes, :bigint, null: false, default: 5_242_880
      add :listing_min_images, :bigint, null: false, default: 1
      add :listing_max_images, :bigint, null: false, default: 10
    end
  end

  def down do
    alter table(:settings) do
      remove :listing_max_images
      remove :listing_min_images
      remove :listing_image_max_bytes
      remove :listing_image_types
      remove :listing_conditions
      remove :currency
      remove :cart_retention_days
    end
  end
end
