defmodule Mercato.Repo.Migrations.AddAccountArchival do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :avatar_key, :text
      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users) do
      remove :archived_at
      remove :avatar_key
    end
  end
end
