defmodule Mercato.Repo.Migrations.AddCartItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cart_items, primary_key: false) do
      add :seller_id,
          references(:users, column: :id, name: "cart_items_seller_id_fkey", type: :uuid),
          null: false

      add :listing_id,
          references(:listings, column: :id, name: "cart_items_listing_id_fkey", type: :uuid),
          null: false

      add :user_id, references(:users, column: :id, name: "cart_items_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :quantity, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:cart_items, [:user_id, :listing_id],
             name: "cart_items_unique_user_listing_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cart_items, [:user_id, :listing_id],
                     name: "cart_items_unique_user_listing_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cart_items` table without the `cart_items_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cart_items` table without the `cart_items_listing_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cart_items` table without the `cart_items_seller_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:cart_items)
  end
end
