defmodule Mercato.Repo.Migrations.CartRetentionInSeconds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      # The window it replaces, in the unit an operator sets it in. Dropped
      # rather than kept: nothing has been set on it that is worth carrying
      # over, since it ships in the same change that added it.
      remove :cart_retention_days

      add :cart_retention_seconds, :bigint, null: false, default: 2_592_000
    end
  end

  def down do
    alter table(:settings) do
      remove :cart_retention_seconds
      add :cart_retention_days, :bigint, null: false, default: 30
    end
  end
end
