defmodule Mercato.Repo.Migrations.AddPermissionAndRolePermissionCreate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:role_permissions, [:role_id, :permission_id],
             name: "role_permissions_unique_role_permission_index"
           )
  end

  def down do
    drop_if_exists unique_index(:role_permissions, [:role_id, :permission_id],
                     name: "role_permissions_unique_role_permission_index"
                   )
  end
end
