defmodule Mercato.Repo.Migrations.AddListingImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:listing_images, primary_key: false) do
      add :listing_id,
          references(:listings, column: :id, name: "listing_images_listing_id_fkey", type: :uuid),
          null: false

      add :created_at, :utc_datetime_usec, null: false
      add :is_cover, :boolean, null: false
      add :position, :bigint, null: false
      add :storage_key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:listing_images, ["listing_id"],
             name: "listing_images_cover_index",
             unique: true,
             where: "is_cover"
           )

    create unique_index(:listing_images, [:listing_id, :position],
             name: "listing_images_unique_position_index"
           )
  end

  def down do
    drop_if_exists unique_index(:listing_images, [:listing_id, :position],
                     name: "listing_images_unique_position_index"
                   )

    drop_if_exists index(:listing_images, ["listing_id"], name: "listing_images_cover_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `listing_images` table without the `listing_images_listing_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:listing_images)
  end
end
