defmodule Mercato.Repo.Migrations.AddRolesPermissionsSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_roles, primary_key: false) do
      add :role_id, references(:roles, column: :id, name: "user_roles_role_id_fkey", type: :uuid),
        primary_key: true,
        null: false

      add :user_id, references(:users, column: :id, name: "user_roles_user_id_fkey", type: :uuid),
        primary_key: true,
        null: false
    end

    create table(:roles, primary_key: false) do
      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:roles, [:name], name: "roles_unique_name_index")

    create table(:role_permissions, primary_key: false) do
      add :permission_id,
          references(:permissions,
            column: :id,
            name: "role_permissions_permission_id_fkey",
            type: :uuid
          ), primary_key: true, null: false

      add :role_id,
          references(:roles, column: :id, name: "role_permissions_role_id_fkey", type: :uuid),
          primary_key: true,
          null: false
    end

    create table(:permissions, primary_key: false) do
      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:permissions, [:name], name: "permissions_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:permissions, [:name], name: "permissions_unique_name_index")

    drop table(:permissions)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `role_permissions` table without the `role_permissions_role_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `role_permissions` table without the `role_permissions_permission_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:role_permissions)

    drop_if_exists unique_index(:roles, [:name], name: "roles_unique_name_index")

    drop table(:roles)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `user_roles` table without the `user_roles_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `user_roles` table without the `user_roles_role_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:user_roles)
  end
end
