defmodule Mercato.Repo.Migrations.AddListingCondition do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:listings) do
      add :condition, :text
    end
  end

  def down do
    alter table(:listings) do
      remove :condition
    end
  end
end
