defmodule Mercato.Repo.Migrations.RelaxFirstNameAndHandleNullability do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`, then
  hand-edited: SQLite has no `ALTER COLUMN`, so relaxing a `NOT NULL`
  constraint requires rebuilding the table.
  """

  use Ecto.Migration

  def up do
    execute("PRAGMA foreign_keys=off")

    execute("""
    CREATE TABLE "users_new" (
      "confirmed_at" TEXT,
      "hashed_password" TEXT,
      "email" CITEXT NOT NULL,
      "id" TEXT NOT NULL PRIMARY KEY,
      "first_name" TEXT,
      "last_name" TEXT,
      "handle" TEXT,
      "handle_changed_at" TEXT,
      "avatar_url" TEXT,
      "status" TEXT NOT NULL,
      "last_active_at" TEXT
    )
    """)

    execute("""
    INSERT INTO "users_new"
    SELECT "confirmed_at", "hashed_password", "email", "id", "first_name",
           "last_name", "handle", "handle_changed_at", "avatar_url", "status",
           "last_active_at"
    FROM "users"
    """)

    drop(table(:users))
    rename(table(:users_new), to: table(:users))

    create(unique_index(:users, [:email], name: "users_unique_email_index"))
    create(unique_index(:users, [:handle], name: "users_unique_handle_index"))

    execute("PRAGMA foreign_keys=on")
  end

  def down do
    execute("PRAGMA foreign_keys=off")

    execute("""
    CREATE TABLE "users_new" (
      "confirmed_at" TEXT,
      "hashed_password" TEXT,
      "email" CITEXT NOT NULL,
      "id" TEXT NOT NULL PRIMARY KEY,
      "first_name" TEXT NOT NULL,
      "last_name" TEXT,
      "handle" TEXT NOT NULL,
      "handle_changed_at" TEXT,
      "avatar_url" TEXT,
      "status" TEXT NOT NULL,
      "last_active_at" TEXT
    )
    """)

    execute("""
    INSERT INTO "users_new"
    SELECT "confirmed_at", "hashed_password", "email", "id", "first_name",
           "last_name", "handle", "handle_changed_at", "avatar_url", "status",
           "last_active_at"
    FROM "users"
    """)

    drop(table(:users))
    rename(table(:users_new), to: table(:users))

    create(unique_index(:users, [:email], name: "users_unique_email_index"))
    create(unique_index(:users, [:handle], name: "users_unique_handle_index"))

    execute("PRAGMA foreign_keys=on")
  end
end
