defmodule Mercato.Repo.Migrations.AddListingCategory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:categories, primary_key: false) do
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:listings) do
      add :category_id,
          references(:categories, column: :id, name: "listings_category_id_fkey", type: :uuid),
          null: false
    end

    create unique_index(:categories, [:slug], name: "categories_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    alter table(:listings) do
      remove :category_id
    end

    drop table(:categories)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `listings` table without the `listings_category_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
