defmodule Mercato.Repo.Migrations.UseAshTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # SQLite refuses a NOT NULL column on a table that already holds rows unless
    # the column carries a default. Each one added below is backfilled with the
    # truest answer available for the rows that predate it; a row created after
    # this migration never falls back to the default, since the resource stamps
    # its own value.
    now = DateTime.utc_now() |> DateTime.to_iso8601()

    # No account recorded when it was opened before this column existed, so the
    # moment the column arrives is the closest honest answer, and it is the same
    # answer for every existing account.
    alter table(:users) do
      add :inserted_at, :utc_datetime_usec, null: false, default: now
      add :updated_at, :utc_datetime_usec, null: false, default: now
    end

    rename table(:listings), :created_at, to: :inserted_at

    rename table(:listing_images), :created_at, to: :inserted_at

    alter table(:listing_images) do
      add :updated_at, :utc_datetime_usec, null: false, default: now
    end

    # An image that predates this column has never been changed through anything
    # that would have stamped it, so the moment it was added is true rather than
    # merely available. Run after the rename above, which is what gives the
    # column its new name.
    execute "UPDATE listing_images SET updated_at = inserted_at"
  end

  def down do
    alter table(:listing_images) do
      remove :updated_at
    end

    rename table(:listing_images), :inserted_at, to: :created_at

    rename table(:listings), :inserted_at, to: :created_at

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
    end
  end
end
